// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2caJ27QlDtDlpXOAlJ0n_m-VH4GyyZ6w',
    appId: '1:59731981386:web:cf8e6c2f53d3044c09a2b3',
    messagingSenderId: '59731981386',
    projectId: 'flameloopmain',
    authDomain: 'flameloopmain.firebaseapp.com',
    storageBucket: 'flameloopmain.appspot.com',
    measurementId: 'G-6P06331SRG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0tD7NGF5pn_7XB3z8XVOblK6h60E5SY8',
    appId: '1:59731981386:android:23aa5f1357a8950709a2b3',
    messagingSenderId: '59731981386',
    projectId: 'flameloopmain',
    storageBucket: 'flameloopmain.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpf44KmrZTbSQM0yuzax7l_JzLWBaN22U',
    appId: '1:59731981386:ios:3dce5eb56a35e62909a2b3',
    messagingSenderId: '59731981386',
    projectId: 'flameloopmain',
    storageBucket: 'flameloopmain.appspot.com',
    iosClientId: '59731981386-eb5h34bb0iipqrnkuv22ajlhbk3nvjl9.apps.googleusercontent.com',
    iosBundleId: 'com.example.flameloop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpf44KmrZTbSQM0yuzax7l_JzLWBaN22U',
    appId: '1:59731981386:ios:3dce5eb56a35e62909a2b3',
    messagingSenderId: '59731981386',
    projectId: 'flameloopmain',
    storageBucket: 'flameloopmain.appspot.com',
    iosClientId: '59731981386-eb5h34bb0iipqrnkuv22ajlhbk3nvjl9.apps.googleusercontent.com',
    iosBundleId: 'com.example.flameloop',
  );
}
